%%
try
    conn=connect_jydb();
    setdbprefs('datareturnformat','table')
    str1=sprintf(['select *  '...
        'from ShengYunDB..V_CreditRating_Every2Week A '...
        'where TradingDay>(select MAX(TradingDay) from ShengYunDB..Q_CreditRatingEvery2Week) '...
        'order by TradingDay,InnerCode '...
        ]);
    curs=exec(conn, str1);
    curs1=fetch(curs);
    RatingRaw = curs1.Data;
    
    %
    Stat = grpstats(RatingRaw,{'TradingDay','InnerCode'},{'median','min'},'DataVars',{'CRCode'});
    %
    V=table2cell(Stat(:,{'TradingDay','InnerCode','median_CRCode','min_CRCode'}));
    %
    write_into_sql_table(V,{'Datetime','Num','Num','Num'},'ShengYunDB..Q_CreditRatingEvery2Week',conn);
catch err
end
%%
try
    
    str1=sprintf(['insert into ShengYunDB..Q_FundamentalRawEvery2Week '...
        'select A.TradingDay '...
        ',C.InnerCode '...
        ',B.EndDate '...
        ',B.NPParentCompanyOwnersTTM '...
        ',B.TotalOperatingRevenueTTM '...
        ',B.OperatingRevenueTTM '...
        ',B.NetOperateCashFlowTTM '...
        ',B.TotalOperatingCostTTM '...
        ',B.OperatingPayoutTTM '...
        ',B.GrossProfitTTM '...
        ',B.InterestBearDebt '...
        ',B.NIFromOperatingTTM '...
        ',B.TotalProfitTTM '...
        ',B.NonoperatingNetIncomeTTM '...
        ',B.NetProfitTTM '...
        ',B.NPDeductNonRecurringPL '...
        ',B_LY2.NPDeductNonRecurringPL as NPDeductNonRecurringPL_LY '...
        ',B_LA.NPDeductNonRecurringPL as NPDeductNonRecurringPL_LA '...
        ',D.SEWithoutMI '...
        ',D.CashEquivalents '...
        ',D.TotalCurrentLiability '...
        ',D.TotalLiability '...
        ',D.TotalAssets '...
        ',D.RetainedProfit '...
        ',ISNULL(E.DivRatio,0) as DivRatio '...
        ',F.Rating_Med '...
        ',F.Rating_Min '...
        ',B_MRA.NPParentCompanyOwnersTTM as NPParY '...
        ',G.TotalCashDiviLTM '...
        ',D_LY.SEWithoutMI as SEWithoutMI_LY '...
        ',D_LY.TotalAssets as TotalAssets_LY '...
        ',B_LY.InterestBearDebt as InterestBearDebt_LY '...
        ',H.MoneyToAccount as PlaceMoney '...
        ',I.MoneyToAccount as IssueMoney '...
        'from ShengYunDB..V_Monday2Week A '...
        'left join ShengYunDB..V_LC_FSDerivedData B '...
        'on B.EndDate=(select MAX(EndDate) from ShengYunDB..V_LC_FSDerivedData where  '...
        'CompanyCode=B.CompanyCode and InfoPublDate<=A.TradingDay and EndDate>=DATEADD(MONTH,-7,A.TradingDay)) '...
        'and B.InfoPublDate=(Select MAX(InfoPublDate) from ShengYunDB..V_LC_FSDerivedData  '...
        'where CompanyCode=B.CompanyCode and InfoPublDate<=A.TradingDay and  '...
        'EndDate=B.EndDate) '...
        'and B.IfAdjusted=(select MIN(IfAdjusted) from ShengYunDB..V_LC_FSDerivedData where  '...
        'CompanyCode=B.CompanyCode and EndDate=B.EndDate and InfoPublDate=B.InfoPublDate) '...
        'inner join ShengYunDB..V_A_Stock_Universe C '...
        'on B.CompanyCode=C.CompanyCode '...
        'left join ShengYunDB..V_LC_BalanceSheetAll D '...
        'on D.CompanyCode=B.CompanyCode '...
        'and D.EndDate=B.EndDate '...
        'and D.InfoPublDate=(select MAX(InfoPublDate) from ShengYunDB..V_LC_BalanceSheetAll  '...
        'where CompanyCode=D.CompanyCode and EndDate=D.EndDate and  '...
        'InfoPublDate<=A.TradingDay) '...
        'and D.IfAdjusted=(select min(IfAdjusted) from ShengYunDB..V_LC_BalanceSheetAll  '...
        'where CompanyCode=D.CompanyCode and EndDate=D.EndDate and  '...
        'InfoPublDate=D.InfoPublDate) '...
        'left join ShengYunDB..Fundamental_CashDividend E '...
        'on C.InnerCode=E.InnerCode  '...
        'and E.EndDate=(select MAX(EndDate) from  '...
        'ShengYunDB..Fundamental_CashDividend where InnerCode=E.InnerCode and ExDiviDate  '...
        'between DATEADD(MONTH,-16,A.TradingDay) and A.TradingDay) '...
        'left join  '...
        'ShengYunDB..Q_CreditRatingEvery2Week F '...
        'on F.TradingDay=A.TradingDay '...
        'and F.InnerCode=C.InnerCode '...
        'left join ShengYunDB..V_EndDate_RK T0 '...
        'on T0.EndDate=B.EndDate '...
        'left join ShengYunDB..V_EndDate_RK T_LY '...
        'on T_LY.RK=T0.RK-4 '...
        'left join ShengYunDB..V_EndDate_RK T_LA '...
        'on T_LA.RK=T0.RK-MONTH(B.EndDate)/3 '...
        'left join ShengYunDB..V_EndDate_RK T_MRA '...
        'on T_MRA.RK=T0.RK-case when MONTH(B.EndDate)/3=4 then 0 else MONTH(B.EndDate)/3 end '...
        'left join ShengYunDB..V_LC_BalanceSheetAll D_LY '...
        'on D_LY.CompanyCode=B.CompanyCode '...
        'and D_LY.EndDate=T_LY.EndDate '...
        'and D_LY.InfoPublDate=(select MAX(InfoPublDate) from  '...
        'ShengYunDB..V_LC_BalanceSheetAll where CompanyCode=D_LY.CompanyCode and  '...
        'EndDate=D_LY.EndDate and InfoPublDate<=A.TradingDay) '...
        'and D_LY.IfAdjusted=(select min(IfAdjusted) from ShengYunDB..V_LC_BalanceSheetAll  '...
        'where CompanyCode=D_LY.CompanyCode and EndDate=D_LY.EndDate and  '...
        'InfoPublDate=D_LY.InfoPublDate) '...
        'left join ShengYunDB..V_LC_FSDerivedData B_MRA '...
        'on B_MRA.CompanyCode=B.CompanyCode '...
        'and B_MRA.EndDate=T_MRA.EndDate '...
        'and B_MRA.InfoPublDate=(Select MAX(InfoPublDate) from  '...
        'ShengYunDB..V_LC_FSDerivedData where CompanyCode=B_MRA.CompanyCode and  '...
        'InfoPublDate<=A.TradingDay and EndDate=B_MRA.EndDate) '...
        'and B_MRA.IfAdjusted=(select MIN(IfAdjusted) from ShengYunDB..V_LC_FSDerivedData  '...
        'where CompanyCode=B_MRA.CompanyCode and EndDate=B_MRA.EndDate and  '...
        'InfoPublDate=B_MRA.InfoPublDate) '...
        'left join ShengYunDB..V_Q_CashDividend G '...
        'on G.InnerCode=C.InnerCode '...
        'and G.EndDate=B_MRA.EndDate '...
        'left join ShengYunDB..V_LC_FSDerivedData B_LY '...
        'on B_LY.CompanyCode=B.CompanyCode '...
        'and B_LY.EndDate=T_LY.EndDate '...
        'and B_LY.InfoPublDate=(Select MAX(InfoPublDate) from ShengYunDB..V_LC_FSDerivedData  '...
        'where CompanyCode=B_LY.CompanyCode and InfoPublDate<=A.TradingDay and  '...
        'EndDate=B_LY.EndDate) '...
        'and B_LY.IfAdjusted=(select MIN(IfAdjusted) from ShengYunDB..V_LC_FSDerivedData  '...
        'where CompanyCode=B_LY.CompanyCode and EndDate=B_LY.EndDate and  '...
        'InfoPublDate=B_LY.InfoPublDate) '...
        'left join ShengYunDB..V_LC_FSDerivedData B_LY2 '...
        'on B_LY2.CompanyCode=B.CompanyCode '...
        'and B_LY2.EndDate=T_LY.EndDate '...
        'and B_LY2.IfAdjusted=2 '...
        'and B_LY2.InfoPublDate=(Select MAX(InfoPublDate) from  '...
        'ShengYunDB..V_LC_FSDerivedData where CompanyCode=B_LY.CompanyCode and  '...
        'InfoPublDate<=A.TradingDay and EndDate=B_LY.EndDate and IfAdjusted=2) '...
        'left join ShengYunDB..V_LC_FSDerivedData B_LA '...
        'on B_LA.CompanyCode=B.CompanyCode '...
        'and B_LA.EndDate=T_LA.EndDate '...
        'and B_LA.InfoPublDate=(Select MAX(InfoPublDate) from ShengYunDB..V_LC_FSDerivedData  '...
        'where CompanyCode=B_LA.CompanyCode and InfoPublDate<=A.TradingDay and  '...
        'EndDate=B_LA.EndDate) '...
        'and B_LA.IfAdjusted=(select MIN(IfAdjusted) from ShengYunDB..V_LC_FSDerivedData  '...
        'where CompanyCode=B_LA.CompanyCode and EndDate=B_LA.EndDate and  '...
        'InfoPublDate=B_LA.InfoPublDate) '...
        'left join ShengYunDB..V_Q_LC_ASharePlacement H '...
        'on H.InnerCode=C.InnerCode '...
        'and H.TradingDay=A.TradingDay '...
        'left join ShengYunDB..V_Q_LC_AShareSeasonedNewIssue I '...
        'on I.InnerCode=C.InnerCode '...
        'and I.TradingDay=A.TradingDay '...
        'where A.TradingDay<=GETDATE() '...
        'and A.TradingDay>(select MAX(TradingDay) from ShengYunDB..Q_FundamentalRawEvery2Week) '...
        ]);
    curs=exec(conn, str1);
    
catch err
end
%%
clear
try
    conn=connect_jydb();
    setdbprefs('datareturnformat','table')
    str1=sprintf(['select * '...
        'from ShengYunDB..V_Q_GrowthRaw  '...
        'where TradingDay>(select MAX(TradingDay) from ShengYunDB..Q_GrowthFactorsEvery2Week) '...
        'order by TradingDay,InnerCode '...
        ]);
    curs=exec(conn, str1);
    curs1=fetch(curs);
    GrowthRaw = curs1.Data;
    
    %
    RevY=table2array(GrowthRaw(:,3:6));
    NPY=table2array(GrowthRaw(:,7:10));
    RevQ=table2array(GrowthRaw(:,11:22));
    NPQ=table2array(GrowthRaw(:,23:34));
    SEQ=table2array(GrowthRaw(:,35:46));
    TAQ=table2array(GrowthRaw(:,47:58));
    %
    G1=mean(2*(RevY(:,1:3)-RevY(:,2:4))./(abs(RevY(:,2:4))+abs(RevY(:,1:3))),2);
    % X1=sum(RevY<0,2)>0;
    % G1(X1)=-99;
    G2=mean(2*(NPY(:,1:3)-NPY(:,2:4))./(abs(NPY(:,2:4))+abs(NPY(:,1:3))),2);
    
    GS1=std((RevQ(:,1:11)-RevQ(:,2:12))./abs(RevQ(:,2:12)),0,2);
    GS2=std((NPQ(:,1:11)-NPQ(:,2:12))./abs(NPQ(:,2:12)),0,2);
    GS3_0=NPQ./SEQ;
    XS3=SEQ<0;
    GS3_0(XS3)=nan;
    GS3=std(GS3_0(:,1:11)-GS3_0(:,2:12),0,2);
    ROE_M3=mean(GS3_0,2);
    GS4_0=NPQ./TAQ;
    GS4=std(GS4_0(:,1:11)-GS4_0(:,2:12),0,2);
    ROA_M3=mean(GS4_0,2);
    
    %
    V=[table2cell(GrowthRaw(:,1:2)),num2cell([G1,G2,GS1,GS2,GS3,GS4,ROE_M3,ROA_M3])];
    %
    write_into_sql_table(V,{'Datetime','Num','Num','Num','Num','Num','Num','Num','Num','Num'},'ShengYunDB..Q_GrowthFactorsEvery2Week',conn);
catch err
end
%%
clear
%
try
    
    conn=connect_jydb();
    setdbprefs('datareturnformat','table')
    str1=sprintf(['select TradingDay,InnerCode,E2P_LTM,B2P from ShengYunDB..V_Q_NonGrowth order by InnerCode,TradingDay '...
        ]);
    curs=exec(conn, str1);
    curs1=fetch(curs);
    EPBPRaw = curs1.Data;
    
    %
    TDList=unique(EPBPRaw.TradingDay);
    TDListN=datenum(TDList,'yyyy-mm-dd');
    
    CodeList=unique(EPBPRaw.InnerCode);
    M3_Cell=cell(size(EPBPRaw));
    %
    C=0;
    for i1=1:length(CodeList)
        T1=EPBPRaw(EPBPRaw.InnerCode==CodeList(i1),:);
        TCN=datenum(T1.TradingDay,'yyyy-mm-dd');
        for i2=1:height(T1)
            C=C+1;
            TEnd=TCN(i2);
            TStart=TDListN(max(find(TDListN==TEnd)-36,1));
            i20=find(TCN==TStart);
            E2P_M3=mean(T1.E2P_LTM(i20:i2));
            B2P_M3=mean(T1.B2P(i20:i2));
            M3_Cell(C,:)=[T1.TradingDay(i2),num2cell([CodeList(i1),E2P_M3,B2P_M3])];
        end
    end
    
    setdbprefs('datareturnformat','table')
    str1=sprintf(['select MAX(TradingDay) as TradingDay from ShengYunDB..Q_M3Every2Week '...
        ]);
    curs=exec(conn, str1);
    curs1=fetch(curs);
    PrevMax = curs1.Data;
    PrevMax=PrevMax.TradingDay{1};
    
    %
    IX=datenum(M3_Cell(:,1),'yyyy-mm-dd')>datenum(PrevMax,'yyyy-mm-dd');
    V=M3_Cell(IX,:);
    
    
    write_into_sql_table(V,{'Datetime','Num','Num','Num'},'ShengYunDB..Q_M3Every2Week',conn);
catch err
end

mailTome('双周更新任务_QualityData',['更新完成,日期:',datestr(now,'yyyy/mm/dd HH:MM:SS')]);
exit
